#--- gaurav-cloud-native-devops-portfolio/phase1-mern-sample/k8s-manifests/frontend.yaml ---#


# Kubernetes Deployment and Service for Frontend #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend # This label should match the selector in the Service
    spec:
      containers:
        - name: frontend
          image: dockergc00/mern-portfolio-frontend:phase1
          imagePullPolicy: Always # Always pull the latest image from docker hub
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend # This selector should match the label in the Deployment pod template
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort # Expose the frontend service via NodePort for external access because there's no Ingress in this setup
